app/components/atoms/pagination/Pagination.tsx
app/hooks/ui/usePagination.ts

feat: 페이지네이션 컴포넌트 및 훅 추가

---

app/layouts/myLikes.tsx

- 소제목 변경
- 호스트 탭 이름 변경
Closes #18

fix: 찜리스트 페이지 잘못된 텍스트 수정

---

app/api/users.ts
app/components/atoms/ProfileImageInput.tsx
app/components/atoms/icons/EditIcon.tsx
app/components/molecules/UserProfileCard.tsx
app/hooks/api/useMyProfileQuery.ts
app/hooks/api/useUpdateProfileMutation.ts
app/hooks/business/useProfileForm.ts
app/routes.ts
app/routes/editProfile.tsx
app/routes/myProfile.tsx

feat: 프로필 수정 페이지 구현

---

app/components/atoms/Banner.tsx
app/components/atoms/SideBarNavItem.tsx
app/components/atoms/SidebarSubNavItem.tsx
app/components/atoms/badge/Badge.tsx
app/components/atoms/logo/Logo.tsx
app/components/atoms/text/Text.tsx
app/components/molecules/InfoItem.tsx
app/components/molecules/SearchInput.tsx
app/components/organisms/CreatedMeetingDetailMeetingDetailContent.tsx
app/components/organisms/MeetingCancelModal.tsx
app/components/organisms/MeetingCard.tsx
app/components/organisms/MeetingDetailContentMiddle.tsx
app/components/organisms/MeetingRevirewContent.tsx
app/components/organisms/Slider.tsx
app/components/organisms/gridGroup/GridGroup.tsx
app/routes/createdMeetingDetailIntro.tsx

- 클래스 명 병합 시 사용하는 모든 clsx를 cn 함수로 교체
Closes #

feat: 클래스 명 병합 시 사용하는 모든 clsx를 cn 함수로 교체

---

app/api/notifications.ts
app/components/molecules/NavbarUserSection.tsx
app/hooks/api/useMyNotificationsQuery.ts

- 상단바에 알림 목록 구현
|        | <img width="426" height="492" alt="image" src="https://github.com/user-attachments/assets/6c25621a-a463-4dd4-ab7b-374b4e71d47c" /> |
Closes #

feat: navbar notification 추가

---

app/components/atoms/tabs/Tabs.tsx
app/components/molecules/HostCard.tsx
app/routes.ts
app/routes/hostLikes.tsx
app/routes/search.tsx

- 검색 페이지 마크업
- api 명세가 없어서 api 작업은 불가

feat: 검색 페이지 마크업

---

app/api/complaints.ts
app/components/molecules/WideReviewCard.tsx
app/components/organisms/ReportForm.tsx
app/constants/api.ts
app/constants/reports.ts
app/hooks/api/useReportComplaintMutation.ts

- 신고 폼 및 api 추가
- 신고 형식이 동일해서 재사용도 가능하지 않을까 생각합니다
|        | ![image](https://github.com/user-attachments/assets/94eda89c-9bb9-4bda-877a-9fb2abdd9fef) |

feat: 신고 기능 추가

---

app/hooks/ui/userUrlFilters.ts

- zod 스키마 기반의 searchparams 파싱, 변경을 위한 커스텀 훅 추가

feat: searchparams 기반 useUrlFilters 훅 추가

---

app/api/users.ts
app/hooks/api/useMyHostLikesQuery.ts
app/routes/myFollowing.tsx
app/types/entities.ts

feat: 팔로잉 리스트 api 연결

---

app/api/users.ts
app/components/organisms/ReviewForm.tsx
app/components/organisms/ReviewableMeetingCard.tsx
app/components/organisms/WrittenReviewCard.tsx
app/hooks/api/useReviewableReviewsQuery.ts
app/hooks/api/useWrittenReviewsQuery.ts
app/routes/reviewableReviews.tsx
app/routes/writtenReviews.tsx

feat: 나의 후기 페이지 api 연결

---

app/components/organisms/CreateMeetingFourthContent.tsx
app/hooks/api/useApplyMeetingMutation.tsx
app/hooks/api/useBreakawayMeetingMutation.tsx
app/hooks/api/useCancelMeetingMutation.tsx
app/hooks/api/useDeclareMeetingOrReviewOrHost.tsx
app/providers/TanstackQueryProvider.tsx
app/root.tsx
app/routes/createdMeeting.tsx

- queryclient 안티 패턴 수정
Closes #58

fix: queryclient 안티 패턴 수정

---

app/config/meta-templates.ts
app/root.tsx
app/routes/createdMeeting.tsx
app/routes/createdMeetingDetailDetail.tsx
app/routes/createdMeetingDetailIntro.tsx
app/routes/createdMeetingDetailManage.tsx
app/routes/guideBookDetail.tsx
app/routes/guideBooks.tsx
app/routes/home.tsx
app/routes/hostDetail.tsx
app/routes/likes.tsx
app/routes/login.tsx
app/routes/loginCallback.tsx
app/routes/meetingDetail.tsx
app/routes/meetings.tsx
app/routes/myFollowing.tsx
app/routes/myInformation.tsx
app/routes/myNotifications.tsx
app/routes/myProfile.tsx
app/routes/participatedMeeting.tsx
app/routes/regularMeetingLikes.tsx
app/routes/requestedMeeting.tsx
app/routes/reviewLikes.tsx
app/routes/reviewableReviews.tsx
app/routes/reviews.tsx
app/routes/search.tsx
app/routes/smallMeetingLikes.tsx
app/routes/writtenReviews.tsx

페이지별 메타데이터 추가(title,description)

---

app/api/searches.ts
app/hooks/api/useSearchGuidebooksQuery.ts
app/hooks/api/useSearchHostsQuery.ts
app/hooks/api/useSearchMeetingsQuery.ts
app/hooks/api/useSearchTotalQuery.ts
app/routes/search.tsx

feat: 검색 api 연결

---

app/routes/meetingDetail.tsx

- meetingDetail 페이지에서 meta 함수의 async 제거
Closes #

fix: meta 함수에서 async 제거

---

app/api/users.ts
app/components/molecules/DatePicker.tsx
app/components/organisms/UserInformationForm.tsx
app/hooks/api/useMyInfoQuery.ts
app/hooks/business/useMyInfoForm.ts
app/routes/myInformation.tsx
app/types/entities.ts

- 개인정보 null로 들어오는 값에 대한 대응, 관련 타입 및 폼 수정
Closes #76

개인정보 수정 null 대응

---

app/components/organisms/ApplyMeetingModal.tsx

- 개인정보를 채우지 않고 모임 신청시 개인정보를 채우고 다시 시도하라는 경고창을 띄웁니다.
|    x    |   <img width="792" height="334" alt="image" src="https://github.com/user-attachments/assets/9ab8e1b0-23ad-4a1e-a5a9-18f4a60a5595" />    |
Closes #80

모임 신청 모달 - 개인정보를 채우지 않고 모임 신청시 경고창 띄우기

---

app/api/users.ts

fix: reviews api written 파라미터 수정

---

app/api/reviews.ts
app/components/molecules/ImageInput.tsx
app/components/molecules/WideReviewCard.tsx
app/components/organisms/MeetingReviewEditModal.tsx
app/components/organisms/ReviewForm.tsx
app/components/organisms/ReviewUpdateForm.tsx
app/components/organisms/WrittenReviewCard.tsx
app/hooks/api/useCreateReviewMutation.ts
app/hooks/api/useDeleteReviewMutation.ts
app/hooks/api/useUpdateReviewMutation.ts
app/schemas/reviews.ts

- ImageInput 컴포넌트 개선
- review api 연결
- review mutation toast 및 invalidate 기능 추가
Closes #

리뷰 api 연결, 폼 개선

---

app/routes/search.tsx

- 검색결과가 없을 때 대체 텍스트 출력
|        |<img width="1504" height="958" alt="image" src="https://github.com/user-attachments/assets/477c946b-3859-4a61-8b12-0a238d5b99fb" />|
Closes #91

검색결과가 없을 때 대체 텍스트 출력

---

app/components/molecules/SearchInput.tsx
app/components/organisms/MeetingFilterControls.tsx
app/components/organisms/Navbar.tsx

- SearchInput 컴포넌트에서 MeetingListFilters 제거
- navbar에서 검색 시 검색 페이지로 이동
Closes #90

navbar 검색 기능 연동

---

app/components/molecules/WideReviewCard.tsx
app/components/organisms/ImageViewerModal.tsx
app/components/organisms/WrittenReviewCard.tsx

- 이미지 사용중인 라이브러리(swiper, radix-ui dialog)를 활용한 리뷰 이미지 보기를 위한 뷰어 컴포넌트 추가
|        |<img width="853" height="1304" alt="localhost_3000_mypage_reviews_written" src="https://github.com/user-attachments/assets/e0172c50-fce0-47e8-a5df-1cb07280dc7a" />|
Closes #

ImageViewer 컴포넌트 추가

---

app/components/molecules/ReviewLikeCard.tsx
app/routes/regularMeetingLikes.tsx
app/routes/smallMeetingLikes.tsx

- 좋아요 페이지 점3개 아이콘 제거,
- 리뷰 카드 ImageViewer 기능 추가
|<img width="976" height="480" alt="image" src="https://github.com/user-attachments/assets/28676ed8-353e-47f9-892f-4aae574804b3" />|<img width="862" height="602" alt="image" src="https://github.com/user-attachments/assets/6035b9a3-3e03-4e3f-b406-9bfb2b1f53ff" />|
|<img width="988" height="578" alt="image" src="https://github.com/user-attachments/assets/14e5eaa1-1357-4174-8113-527b09511313" />|<img width="990" height="454" alt="image" src="https://github.com/user-attachments/assets/06e9202a-c7aa-4290-945e-c58263940602" />|
Closes #111

좋아요 페이지 점3개 아이콘 제거, ImageViewer 추가

---

app/components/molecules/HostCard.tsx
app/routes/search.tsx

검색 결과 페이지에서 모임, 호스트 좋아요 가능하도록 수정

---

app/constants/roles.ts
app/middlewares/auth.ts

- 역할 기반 경로 보호를 위한 미들웨어 추가
Closes #

Role 기반 미들웨어 구현

---

app/root.tsx
app/styles/app.css

- 에러 바운더리 디자인 개선
|<img width="812" height="448" alt="image" src="https://github.com/user-attachments/assets/054254a4-82ee-438c-b0b9-55c85480ec9d" />|<img width="564" height="442" alt="image" src="https://github.com/user-attachments/assets/0614f7d8-ad41-4032-b65c-6e00933ec1fe" />|
Closes #127

에러 바운더리 디자인 개선
